# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-02-03 00:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_number', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=30, verbose_name=b'Item Name')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=7)),
                ('quantity', models.IntegerField()),
                ('hidden', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='TransactionLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateTimeField(auto_now_add=True)),
                ('entry_type', models.CharField(choices=[(b'SHP', b'Shipped'), (b'RCV', b'Received'), (b'IAD', b'Added Item'), (b'IDL', b'Deleted Item'), (b'VAD', b'Added Vendor'), (b'VDL', b'Deleted Vendor')], max_length=3)),
                ('entity_number', models.IntegerField(blank=True, null=True)),
                ('entity_quantity', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='vendor_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.Vendor'),
        ),
    ]
